#!/bin/sh
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#Afgeleid van proprietary-files
#K00F-vendor-blobs.mk onder aan nakijken op missende: \
VENDOR=asus
DEVICE=K00F
#MANUFACTURER=Asus
#mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/bin
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/bluetooth
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/dhcpcd/dhcpcd-hooks
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/rtlbt
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/updatecmds
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/usb_modeswitch.d
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/ppp
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/ril
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/etc/wifi
#mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/fonts
#mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/fonts/AdobeFonts/fonts
#mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/fonts/AdobeFonts/hyphenDicts
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/framework
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/lib/egl
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/lib/soundfx
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/lib/ssl/engines
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/media/audio/alarms
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/media/audio/notifications
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/media/audio/ringtones
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/media/audio/ui
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/idc
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/keychars
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/cards
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/init
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/zoneinfo
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/config
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/hwr/HK
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/hwr/PRC
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/mdb
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/vendor/etc
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/vendor/lib/drm
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N
mkdir -p ../../../device/$VENDOR/$DEVICE/proprietary/xbin

cp -a src/lib/libril.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libril.so
cp -a src/bin/am ../../../device/$VENDOR/$DEVICE/proprietary/bin/am
cp -a src/bin/abcc ../../../device/$VENDOR/$DEVICE/proprietary/bin/abcc
cp -a src/bin/applypatch ../../../device/$VENDOR/$DEVICE/proprietary/bin/applypatch
cp -a src/bin/asusrmdir.sh ../../../device/$VENDOR/$DEVICE/proprietary/bin/asusrmdir.sh
cp -a src/bin/asusrmdir1.sh ../../../device/$VENDOR/$DEVICE/proprietary/bin/asusrmdir1.sh
cp -a src/bin/atrace ../../../device/$VENDOR/$DEVICE/proprietary/bin/atrace
cp -a src/bin/awk ../../../device/$VENDOR/$DEVICE/proprietary/bin/awk
cp -a src/bin/bmgr ../../../device/$VENDOR/$DEVICE/proprietary/bin/bmgr
cp -a src/bin/bootanimation ../../../device/$VENDOR/$DEVICE/proprietary/bin/bootanimation
cp -a src/bin/brcm_patchram_plus ../../../device/$VENDOR/$DEVICE/proprietary/bin/brcm_patchram_plus
cp -a src/bin/bu ../../../device/$VENDOR/$DEVICE/proprietary/bin/bu
cp -a src/bin/dd ../../../device/$VENDOR/$DEVICE/proprietary/bin/dd
cp -a src/bin/bugmailer.sh ../../../device/$VENDOR/$DEVICE/proprietary/bin/bugmailer.sh
cp -a src/bin/busybox ../../../device/$VENDOR/$DEVICE/proprietary/bin/busybox
cp -a src/bin/cat ../../../device/$VENDOR/$DEVICE/proprietary/bin/cat
cp -a src/bin/ChargerModSwitch.sh ../../../device/$VENDOR/$DEVICE/proprietary/bin/ChargerModSwitch.sh
cp -a src/bin/chat ../../../device/$VENDOR/$DEVICE/proprietary/bin/chat
cp -a src/bin/chmod ../../../device/$VENDOR/$DEVICE/proprietary/bin/chmod
cp -a src/bin/chown ../../../device/$VENDOR/$DEVICE/proprietary/bin/chown
cp -a src/bin/cmp ../../../device/$VENDOR/$DEVICE/proprietary/bin/cmp
cp -a src/bin/content ../../../device/$VENDOR/$DEVICE/proprietary/bin/content
cp -a src/bin/cp ../../../device/$VENDOR/$DEVICE/proprietary/bin/cp
cp -a src/bin/dalvikvm ../../../device/$VENDOR/$DEVICE/proprietary/bin/dalvikvm
cp -a src/bin/date ../../../device/$VENDOR/$DEVICE/proprietary/bin/date
cp -a src/bin/debuggerd ../../../device/$VENDOR/$DEVICE/proprietary/bin/debuggerd
cp -a src/bin/dexopt ../../../device/$VENDOR/$DEVICE/proprietary/bin/dexopt
cp -a src/bin/df ../../../device/$VENDOR/$DEVICE/proprietary/bin/df
cp -a src/bin/dhcpcd ../../../device/$VENDOR/$DEVICE/proprietary/bin/dhcpcd
cp -a src/bin/dmesg ../../../device/$VENDOR/$DEVICE/proprietary/bin/dmesg
cp -a src/bin/dnsmasq ../../../device/$VENDOR/$DEVICE/proprietary/bin/dnsmasq
cp -a src/bin/drmserver ../../../device/$VENDOR/$DEVICE/proprietary/bin/drmserver
cp -a src/bin/drmservice ../../../device/$VENDOR/$DEVICE/proprietary/bin/drmservice
cp -a src/bin/du ../../../device/$VENDOR/$DEVICE/proprietary/bin/du
cp -a src/bin/dumpstate ../../../device/$VENDOR/$DEVICE/proprietary/bin/dumpstate
cp -a src/bin/dumpsys ../../../device/$VENDOR/$DEVICE/proprietary/bin/dumpsys
cp -a src/bin/e2fsck ../../../device/$VENDOR/$DEVICE/proprietary/bin/e2fsck
cp -a src/bin/exfatck ../../../device/$VENDOR/$DEVICE/proprietary/bin/exfatck
cp -a src/bin/exfatlabel ../../../device/$VENDOR/$DEVICE/proprietary/bin/exfatlabel
cp -a src/bin/fsck_msdos ../../../device/$VENDOR/$DEVICE/proprietary/bin/fsck_msdos
cp -a src/bin/GammaSetting ../../../device/$VENDOR/$DEVICE/proprietary/bin/GammaSetting
cp -a src/bin/getevent ../../../device/$VENDOR/$DEVICE/proprietary/bin/getevent
cp -a src/bin/getprop ../../../device/$VENDOR/$DEVICE/proprietary/bin/getprop
cp -a src/bin/gpsd ../../../device/$VENDOR/$DEVICE/proprietary/bin/gpsd
cp -a src/bin/grep ../../../device/$VENDOR/$DEVICE/proprietary/bin/grep
cp -a src/bin/gsm0710muxd ../../../device/$VENDOR/$DEVICE/proprietary/bin/gsm0710muxd
cp -a src/bin/gsm0710muxd_a85xx ../../../device/$VENDOR/$DEVICE/proprietary/bin/gsm0710muxd_a85xx
cp -a src/bin/gsm0710muxd_c66a ../../../device/$VENDOR/$DEVICE/proprietary/bin/gsm0710muxd_c66a
cp -a src/bin/gsm0710muxd_m51 ../../../device/$VENDOR/$DEVICE/proprietary/bin/gsm0710muxd_m51
cp -a src/bin/gsm0710muxd_mt6250 ../../../device/$VENDOR/$DEVICE/proprietary/bin/gsm0710muxd_mt6250
cp -a src/bin/gzip ../../../device/$VENDOR/$DEVICE/proprietary/bin/gzip
cp -a src/bin/hd ../../../device/$VENDOR/$DEVICE/proprietary/bin/hd
cp -a src/bin/hostapd ../../../device/$VENDOR/$DEVICE/proprietary/bin/hostapd
cp -a src/bin/id ../../../device/$VENDOR/$DEVICE/proprietary/bin/id
cp -a src/bin/ifconfig ../../../device/$VENDOR/$DEVICE/proprietary/bin/ifconfig
cp -a src/bin/iftop ../../../device/$VENDOR/$DEVICE/proprietary/bin/iftop
cp -a src/bin/ime ../../../device/$VENDOR/$DEVICE/proprietary/bin/ime
cp -a src/bin/input ../../../device/$VENDOR/$DEVICE/proprietary/bin/input
cp -a src/bin/insmod ../../../device/$VENDOR/$DEVICE/proprietary/bin/insmod
cp -a src/bin/installd ../../../device/$VENDOR/$DEVICE/proprietary/bin/installd
cp -a src/bin/ioctl ../../../device/$VENDOR/$DEVICE/proprietary/bin/ioctl
cp -a src/bin/ionice ../../../device/$VENDOR/$DEVICE/proprietary/bin/ionice
cp -a src/bin/ip ../../../device/$VENDOR/$DEVICE/proprietary/bin/ip
cp -a src/bin/ip6tables ../../../device/$VENDOR/$DEVICE/proprietary/bin/ip6tables
cp -a src/bin/iptables ../../../device/$VENDOR/$DEVICE/proprietary/bin/iptables
cp -a src/bin/iwconfig ../../../device/$VENDOR/$DEVICE/proprietary/bin/iwconfig
cp -a src/bin/iwlist ../../../device/$VENDOR/$DEVICE/proprietary/bin/iwlist
cp -a src/bin/keystore ../../../device/$VENDOR/$DEVICE/proprietary/bin/keystore
cp -a src/bin/kill ../../../device/$VENDOR/$DEVICE/proprietary/bin/kill
cp -a src/bin/linker ../../../device/$VENDOR/$DEVICE/proprietary/bin/linker
cp -a src/bin/ln ../../../device/$VENDOR/$DEVICE/proprietary/bin/ln
cp -a src/bin/log ../../../device/$VENDOR/$DEVICE/proprietary/bin/log
cp -a src/bin/logcat ../../../device/$VENDOR/$DEVICE/proprietary/bin/logcat
cp -a src/bin/logwrapper ../../../device/$VENDOR/$DEVICE/proprietary/bin/logwrapper
cp -a src/bin/ls ../../../device/$VENDOR/$DEVICE/proprietary/bin/ls
cp -a src/bin/lsmod ../../../device/$VENDOR/$DEVICE/proprietary/bin/lsmod
cp -a src/bin/lsof ../../../device/$VENDOR/$DEVICE/proprietary/bin/lsof
cp -a src/bin/make_ext4fs ../../../device/$VENDOR/$DEVICE/proprietary/bin/make_ext4fs
cp -a src/bin/md5 ../../../device/$VENDOR/$DEVICE/proprietary/bin/md5
cp -a src/bin/mdnsd ../../../device/$VENDOR/$DEVICE/proprietary/bin/mdnsd
cp -a src/bin/mediaserver ../../../device/$VENDOR/$DEVICE/proprietary/bin/mediaserver
cp -a src/bin/mkdir ../../../device/$VENDOR/$DEVICE/proprietary/bin/mkdir
cp -a src/bin/mkexfat ../../../device/$VENDOR/$DEVICE/proprietary/bin/mkexfat
cp -a src/bin/mkntfs ../../../device/$VENDOR/$DEVICE/proprietary/bin/mkntfs
cp -a src/bin/mksh ../../../device/$VENDOR/$DEVICE/proprietary/bin/mksh
cp -a src/bin/monkey ../../../device/$VENDOR/$DEVICE/proprietary/bin/monkey
cp -a src/bin/mount ../../../device/$VENDOR/$DEVICE/proprietary/bin/mount
cp -a src/bin/mtpd ../../../device/$VENDOR/$DEVICE/proprietary/bin/mtpd
cp -a src/bin/mv ../../../device/$VENDOR/$DEVICE/proprietary/bin/mv
cp -a src/bin/nandread ../../../device/$VENDOR/$DEVICE/proprietary/bin/nandread
cp -a src/bin/ndc ../../../device/$VENDOR/$DEVICE/proprietary/bin/ndc
cp -a src/bin/netcfg ../../../device/$VENDOR/$DEVICE/proprietary/bin/netcfg
cp -a src/bin/netd ../../../device/$VENDOR/$DEVICE/proprietary/bin/netd
cp -a src/bin/netstat ../../../device/$VENDOR/$DEVICE/proprietary/bin/netstat
cp -a src/bin/newfs_msdos ../../../device/$VENDOR/$DEVICE/proprietary/bin/newfs_msdos
cp -a src/bin/notify ../../../device/$VENDOR/$DEVICE/proprietary/bin/notify
cp -a src/bin/ntfsck ../../../device/$VENDOR/$DEVICE/proprietary/bin/ntfsck
cp -a src/bin/ntfsdebug ../../../device/$VENDOR/$DEVICE/proprietary/bin/ntfsdebug
cp -a src/bin/ntfsinfo ../../../device/$VENDOR/$DEVICE/proprietary/bin/ntfsinfo
cp -a src/bin/ntfslabel ../../../device/$VENDOR/$DEVICE/proprietary/bin/ntfslabel
cp -a src/bin/pbtest ../../../device/$VENDOR/$DEVICE/proprietary/bin/pbtest
cp -a src/bin/performance ../../../device/$VENDOR/$DEVICE/proprietary/bin/performance
cp -a src/bin/ping ../../../device/$VENDOR/$DEVICE/proprietary/bin/ping
cp -a src/bin/pm ../../../device/$VENDOR/$DEVICE/proprietary/bin/pm
cp -a src/bin/pppd ../../../device/$VENDOR/$DEVICE/proprietary/bin/pppd
cp -a src/bin/prebugreport ../../../device/$VENDOR/$DEVICE/proprietary/bin/prebugreport
cp -a src/bin/printenv ../../../device/$VENDOR/$DEVICE/proprietary/bin/printenv
cp -a src/bin/ps ../../../device/$VENDOR/$DEVICE/proprietary/bin/ps
cp -a src/bin/racoon ../../../device/$VENDOR/$DEVICE/proprietary/bin/racoon
cp -a src/bin/reboot ../../../device/$VENDOR/$DEVICE/proprietary/bin/reboot
cp -a src/bin/renice ../../../device/$VENDOR/$DEVICE/proprietary/bin/renice
cp -a src/bin/requestsync ../../../device/$VENDOR/$DEVICE/proprietary/bin/requestsync
cp -a src/bin/rild ../../../device/$VENDOR/$DEVICE/proprietary/bin/rild
cp -a src/bin/rild3 ../../../device/$VENDOR/$DEVICE/proprietary/bin/rild3
cp -a src/bin/rm ../../../device/$VENDOR/$DEVICE/proprietary/bin/rm
cp -a src/bin/rmdir ../../../device/$VENDOR/$DEVICE/proprietary/bin/rmdir
cp -a src/bin/rmmod ../../../device/$VENDOR/$DEVICE/proprietary/bin/rmmod
cp -a src/bin/route ../../../device/$VENDOR/$DEVICE/proprietary/bin/route
cp -a src/bin/run-as ../../../device/$VENDOR/$DEVICE/proprietary/bin/run-as
cp -a src/bin/schedtest ../../../device/$VENDOR/$DEVICE/proprietary/bin/schedtest
cp -a src/bin/schedtop ../../../device/$VENDOR/$DEVICE/proprietary/bin/schedtop
cp -a src/bin/screencap ../../../device/$VENDOR/$DEVICE/proprietary/bin/screencap
cp -a src/bin/screenshot ../../../device/$VENDOR/$DEVICE/proprietary/bin/screenshot
cp -a src/bin/sdcard ../../../device/$VENDOR/$DEVICE/proprietary/bin/sdcard
cp -a src/bin/send_bug ../../../device/$VENDOR/$DEVICE/proprietary/bin/send_bug
cp -a src/bin/sendevent ../../../device/$VENDOR/$DEVICE/proprietary/bin/sendevent
cp -a src/bin/sensorservice ../../../device/$VENDOR/$DEVICE/proprietary/bin/sensorservice
cp -a src/bin/service ../../../device/$VENDOR/$DEVICE/proprietary/bin/service
cp -a src/bin/servicemanager ../../../device/$VENDOR/$DEVICE/proprietary/bin/servicemanager
cp -a src/bin/setconsole ../../../device/$VENDOR/$DEVICE/proprietary/bin/setconsole
cp -a src/bin/setprop ../../../device/$VENDOR/$DEVICE/proprietary/bin/setprop
cp -a src/bin/settings ../../../device/$VENDOR/$DEVICE/proprietary/bin/settings
cp -a src/bin/sh ../../../device/$VENDOR/$DEVICE/proprietary/bin/sh
cp -a src/bin/sleep ../../../device/$VENDOR/$DEVICE/proprietary/bin/sleep
cp -a src/bin/smd ../../../device/$VENDOR/$DEVICE/proprietary/bin/smd
cp -a src/bin/start ../../../device/$VENDOR/$DEVICE/proprietary/bin/start
cp -a src/bin/stop ../../../device/$VENDOR/$DEVICE/proprietary/bin/stop
cp -a src/bin/surfaceflinger ../../../device/$VENDOR/$DEVICE/proprietary/bin/surfaceflinger
cp -a src/bin/svc ../../../device/$VENDOR/$DEVICE/proprietary/bin/svc
cp -a src/bin/sync ../../../device/$VENDOR/$DEVICE/proprietary/bin/sync
cp -a src/bin/system_server ../../../device/$VENDOR/$DEVICE/proprietary/bin/system_server
cp -a src/bin/tc ../../../device/$VENDOR/$DEVICE/proprietary/bin/tc
cp -a src/bin/texfatdebug ../../../device/$VENDOR/$DEVICE/proprietary/bin/texfatdebug
cp -a src/bin/texfatinfo ../../../device/$VENDOR/$DEVICE/proprietary/bin/texfatinfo
cp -a src/bin/toolbox ../../../device/$VENDOR/$DEVICE/proprietary/bin/toolbox
cp -a src/bin/top ../../../device/$VENDOR/$DEVICE/proprietary/bin/top
cp -a src/bin/touch ../../../device/$VENDOR/$DEVICE/proprietary/bin/touch
cp -a src/bin/uiautomator ../../../device/$VENDOR/$DEVICE/proprietary/bin/uiautomator
cp -a src/bin/umount ../../../device/$VENDOR/$DEVICE/proprietary/bin/umount
cp -a src/bin/uptime ../../../device/$VENDOR/$DEVICE/proprietary/bin/uptime
cp -a src/bin/usb_modeswitch ../../../device/$VENDOR/$DEVICE/proprietary/bin/usb_modeswitch
cp -a src/bin/usb_modeswitch.sh ../../../device/$VENDOR/$DEVICE/proprietary/bin/usb_modeswitch.sh
cp -a src/bin/vdc ../../../device/$VENDOR/$DEVICE/proprietary/bin/vdc
cp -a src/bin/vold ../../../device/$VENDOR/$DEVICE/proprietary/bin/vold
cp -a src/bin/vmstat ../../../device/$VENDOR/$DEVICE/proprietary/bin/vmstat
cp -a src/bin/watchprops ../../../device/$VENDOR/$DEVICE/proprietary/bin/watchprops
cp -a src/bin/wfd ../../../device/$VENDOR/$DEVICE/proprietary/bin/wfd
cp -a src/bin/whtest.sh ../../../device/$VENDOR/$DEVICE/proprietary/bin/whtest.sh
cp -a src/bin/wipe ../../../device/$VENDOR/$DEVICE/proprietary/bin/wipe
cp -a src/bin/wpa_supplicant ../../../device/$VENDOR/$DEVICE/proprietary/bin/wpa_supplicant
cp -a src/etc/alarm_filter.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/alarm_filter.xml
cp -a src/etc/amazon-kindle.properties ../../../device/$VENDOR/$DEVICE/proprietary/etc/amazon-kindle.properties
cp -a src/etc/apns-conf.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/apns-conf.xml
cp -a src/etc/asound.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/asound.conf
cp -a src/etc/audio_effects.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/audio_effects.conf
cp -a src/etc/audio_effects_.mps ../../../device/$VENDOR/$DEVICE/proprietary/etc/audio_effects_.mps
cp -a src/etc/audio_policy.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/audio_policy.conf
cp -a src/etc/cpu-balance.sh ../../../device/$VENDOR/$DEVICE/proprietary/etc/cpu-balance.sh
cp -a src/etc/cpu-normal.sh ../../../device/$VENDOR/$DEVICE/proprietary/etc/cpu-normal.sh
cp -a src/etc/cpu-power-saving.sh ../../../device/$VENDOR/$DEVICE/proprietary/etc/cpu-power-saving.sh
cp -a src/etc/dbus.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/dbus.conf
cp -a src/etc/event-log-tags ../../../device/$VENDOR/$DEVICE/proprietary/etc/event-log-tags
cp -a src/etc/fallback_fonts.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/fallback_fonts.xml
cp -a src/etc/floating-res.apk ../../../device/$VENDOR/$DEVICE/proprietary/etc/floating-res.apk
cp -a src/etc/gps.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/gps.conf
cp -a src/etc/gpsconfig.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/gpsconfig.xml
cp -a src/etc/hosts ../../../device/$VENDOR/$DEVICE/proprietary/etc/hosts
cp -a src/etc/init.asus.audbg.sh ../../../device/$VENDOR/$DEVICE/proprietary/etc/init.asus.audbg.sh
cp -a src/etc/init.goldfish.sh ../../../device/$VENDOR/$DEVICE/proprietary/etc/init.goldfish.sh
cp -a src/etc/libgps.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/libgps.conf
cp -a src/etc/media_codecs.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/media_codecs.xml
cp -a src/etc/media_profiles.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/media_profiles.xml
cp -a src/etc/mkshrc ../../../device/$VENDOR/$DEVICE/proprietary/etc/mkshrc
cp -a src/etc/NOTICE.html.gz ../../../device/$VENDOR/$DEVICE/proprietary/etc/NOTICE.html.gz
cp -a src/etc/operator_table ../../../device/$VENDOR/$DEVICE/proprietary/etc/operator_table
cp -a src/etc/packages-compat.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/packages-compat.xml
cp -a src/etc/packages-composer.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/packages-composer.xml
cp -a src/etc/performance_info.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/performance_info.xml
cp -a src/etc/recovery-resource.dat ../../../device/$VENDOR/$DEVICE/proprietary/etc/recovery-resource.dat
cp -a src/etc/spn-conf.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/spn-conf.xml
cp -a src/etc/system_fonts.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/system_fonts.xml
cp -a src/etc/videoplay.sh ../../../device/$VENDOR/$DEVICE/proprietary/etc/videoplay.sh
cp -a src/etc/vold.fstab ../../../device/$VENDOR/$DEVICE/proprietary/etc/vold.fstab
cp -a src/etc/web_browsing.sh ../../../device/$VENDOR/$DEVICE/proprietary/etc/web_browsing.sh
cp -a src/etc/bluetooth/auto_pair_devlist.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/bluetooth/auto_pair_devlist.conf
cp -a src/etc/bluetooth/bt_did.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/bluetooth/bt_did.conf
cp -a src/etc/bluetooth/bt_stack.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/bluetooth/bt_stack.conf
cp -a src/etc/dhcpcd/dhcpcd.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/dhcpcd/dhcpcd.conf
cp -a src/etc/dhcpcd/dhcpcd-run-hooks ../../../device/$VENDOR/$DEVICE/proprietary/etc/dhcpcd/dhcpcd-run-hooks
cp -a src/etc/dhcpcd/dhcpcd-hooks/20-dns.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/dhcpcd/dhcpcd-hooks/20-dns.conf
cp -a src/etc/dhcpcd/dhcpcd-hooks/95-configured ../../../device/$VENDOR/$DEVICE/proprietary/etc/dhcpcd/dhcpcd-hooks/95-configured
cp -a src/etc/firmware/arcsoft_ff_config.dat ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/arcsoft_ff_config.dat
cp -a src/etc/firmware/fw_bcm4330.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_bcm4330.bin
cp -a src/etc/firmware/fw_bcm4330_apsta.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_bcm4330_apsta.bin
cp -a src/etc/firmware/fw_RK901.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK901.bin
cp -a src/etc/firmware/fw_RK901a0.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK901a0.bin
cp -a src/etc/firmware/fw_RK901a0_apsta.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK901a0_apsta.bin
cp -a src/etc/firmware/fw_RK901a2.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK901a2.bin
cp -a src/etc/firmware/fw_RK901a2_apsta.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK901a2_apsta.bin
cp -a src/etc/firmware/fw_RK901a2_p2p.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK901a2_p2p.bin
cp -a src/etc/firmware/fw_RK903.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK903.bin
cp -a src/etc/firmware/fw_RK903_ag.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK903_ag.bin
cp -a src/etc/firmware/fw_RK903_ag_apsta.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK903_ag_apsta.bin
cp -a src/etc/firmware/fw_RK903_ag_p2p.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK903_ag_p2p.bin
cp -a src/etc/firmware/fw_RK903b2.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK903b2.bin
cp -a src/etc/firmware/fw_RK903b2_apsta.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK903b2_apsta.bin
cp -a src/etc/firmware/fw_RK903b2_p2p.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK903b2_p2p.bin
cp -a src/etc/firmware/fw_RK903_p2p.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/fw_RK903_p2p.bin
cp -a src/etc/firmware/icatch7002boot.bin ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/icatch7002boot.bin
cp -a src/etc/firmware/MTK_MT6622_E2_Patch.nb0 ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/MTK_MT6622_E2_Patch.nb0
cp -a src/etc/firmware/nvram.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram.txt
cp -a src/etc/firmware/nvram_4330.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_4330.txt
cp -a src/etc/firmware/nvram_AP6181.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_AP6181.txt
cp -a src/etc/firmware/nvram_AP6210.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_AP6210.txt
cp -a src/etc/firmware/nvram_AP6330.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_AP6330.txt
cp -a src/etc/firmware/nvram_AP6476.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_AP6476.txt
cp -a src/etc/firmware/nvram_AP6493.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_AP6493.txt
cp -a src/etc/firmware/nvram_B23.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_B23.txt
cp -a src/etc/firmware/nvram_GB86302I.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_GB86302I.txt
cp -a src/etc/firmware/nvram_RK901.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_RK901.txt
cp -a src/etc/firmware/nvram_RK903.cal ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_RK903.cal
cp -a src/etc/firmware/nvram_RK903.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_RK903.txt
cp -a src/etc/firmware/nvram_RK903_26M.cal ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/nvram_RK903_26M.cal
cp -a src/etc/firmware/otp.bin.z77 ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/otp.bin.z77
cp -a src/etc/firmware/RT2870AP.dat ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/RT2870AP.dat
cp -a src/etc/firmware/RT2870APCard.dat ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/RT2870APCard.dat
cp -a src/etc/firmware/RT2870STA.dat ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/RT2870STA.dat
cp -a src/etc/firmware/RT2870STACard.dat ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/RT2870STACard.dat
cp -a src/etc/firmware/RT5370AP.dat ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/RT5370AP.dat
cp -a src/etc/firmware/RT5370STA.dat ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/RT5370STA.dat
cp -a src/etc/firmware/WIFI_RAM_CODE ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/WIFI_RAM_CODE
cp -a src/etc/firmware/rtlbt/rtlbt_config ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/rtlbt/rtlbt_config
cp -a src/etc/firmware/rtlbt/rtlbt_fw ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/rtlbt/rtlbt_fw
cp -a src/etc/firmware/Splendid/asussplendid_config.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/asussplendid_config.xml
cp -a src/etc/firmware/Splendid/LUT/LUT_C01.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C01.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_C02.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C02.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_C03.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C03.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_C04.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C04.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_C05.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C05.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_C06.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C06.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_C07.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C07.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_C08.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C08.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_C09.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C09.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_C10.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_C10.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_DEF.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_DEF.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_RdStrong.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_RdStrong.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_RdWeak.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_RdWeak.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W01.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W01.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W02.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W02.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W03.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W03.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W04.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W04.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W05.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W05.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W06.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W06.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W07.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W07.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W08.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W08.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W09.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W09.txt
cp -a src/etc/firmware/Splendid/LUT/LUT_W10.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/firmware/Splendid/LUT/LUT_W10.txt
cp -a src/etc/permissions/android.hardware.location.gps.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/android.hardware.location.gps.xml
cp -a src/etc/permissions/android.hardware.location.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/android.hardware.location.xml
cp -a src/etc/permissions/android.hardware.sensor.compass.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/android.hardware.sensor.compass.xml
cp -a src/etc/permissions/android.hardware.wifi.direct.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/android.hardware.wifi.direct.xml
cp -a src/etc/permissions/android.software.live_wallpaper.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/android.software.live_wallpaper.xml
cp -a src/etc/permissions/asus.hardware.sound.maxxaudio.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/asus.hardware.sound.maxxaudio.xml
cp -a src/etc/permissions/com.android.location.provider.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/com.android.location.provider.xml
cp -a src/etc/permissions/com.asus.ui.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/com.asus.ui.xml
cp -a src/etc/permissions/com.google.android.maps.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/com.google.android.maps.xml
cp -a src/etc/permissions/com.google.android.media.effects.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/com.google.android.media.effects.xml
cp -a src/etc/permissions/com.google.widevine.software.drm.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/com.google.widevine.software.drm.xml
cp -a src/etc/permissions/rk-camera.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/rk-camera.xml
cp -a src/etc/permissions/rk-camera-front.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/rk-camera-front.xml
cp -a src/etc/permissions/rk-core.xml ../../../device/$VENDOR/$DEVICE/proprietary/etc/permissions/rk-core.xml
cp -a src/etc/ppp/call-pppd ../../../device/$VENDOR/$DEVICE/proprietary/etc/ppp/call-pppd
cp -a src/etc/ppp/ip-down ../../../device/$VENDOR/$DEVICE/proprietary/etc/ppp/ip-down
cp -a src/etc/ppp/ip-up ../../../device/$VENDOR/$DEVICE/proprietary/etc/ppp/ip-up
cp -a src/etc/ppp/ip-up-vpn ../../../device/$VENDOR/$DEVICE/proprietary/etc/ppp/ip-up-vpn
cp -a src/etc/updatecmds/google_generic_update.txt ../../../device/$VENDOR/$DEVICE/proprietary/etc/updatecmds/google_generic_update.txt
cp -a src/etc/usb_modeswitch.d/0ace_20ff ../../../device/$VENDOR/$DEVICE/proprietary/etc/usb_modeswitch.d/0ace_20ff
cp -a src/etc/wifi/wpa_supplicant.conf ../../../device/$VENDOR/$DEVICE/proprietary/etc/wifi/wpa_supplicant.conf
cp -a src/framework/asus-ui.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/asus-ui.jar
cp -a src/framework/content.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/content.jar
cp -a src/framework/mms-common.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/mms-common.jar
cp -a src/framework/requestsync.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/requestsync.jar
cp -a src/framework/telephony-common.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/telephony-common.jar
cp -a src/framework/uiautomator.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/uiautomator.jar
cp -a src/scripts/monkey/blacklist.txt ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey/blacklist.txt
cp -a src/scripts/monkey/EmptyActivity.obj ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey/EmptyActivity.obj
cp -a src/scripts/monkey/monkey_sh ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey/monkey_sh
cp -a src/scripts/monkey/monkey_test_a ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey/monkey_test_a
cp -a src/scripts/monkey/monkey_test_p ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey/monkey_test_p
cp -a src/scripts/monkey/package_list.txt ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey/package_list.txt
cp -a src/scripts/monkey/profiling ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey/profiling
cp -a src/scripts/monkey/TestIME.obj ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey/TestIME.obj
cp -a src/scripts/monkey/timer ../../../device/$VENDOR/$DEVICE/proprietary/scripts/monkey/timer
cp -a src/framework/com.android.future.usb.accessory.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/com.android.future.usb.accessory.jar
cp -a src/framework/com.google.android.maps.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/com.google.android.maps.jar
cp -a src/framework/com.google.android.media.effects.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/com.google.android.media.effects.jar
cp -a src/framework/send_bug.jar ../../../device/$VENDOR/$DEVICE/proprietary/framework/send_bug.jar
cp -a src/lib/crtbegin_so.o ../../../device/$VENDOR/$DEVICE/proprietary/lib/crtbegin_so.o
cp -a src/lib/crtend_so.o ../../../device/$VENDOR/$DEVICE/proprietary/lib/crtend_so.o
cp -a src/lib/libAndroidExport.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libAndroidExport.so
cp -a src/lib/libAppDataSearch.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libAppDataSearch.so
cp -a src/lib/libCxImageKRF.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libCxImageKRF.so
cp -a src/lib/libEGL.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libEGL.so
cp -a src/lib/libETC1.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libETC1.so
cp -a src/lib/libFFTEm.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libFFTEm.so
cp -a src/lib/libGLES_trace.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libGLES_trace.so
cp -a src/lib/libGLESv1_CM.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libGLESv1_CM.so
cp -a src/lib/libGLESv2.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libGLESv2.so
cp -a src/lib/libImageEffects.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libImageEffects.so
cp -a src/lib/libKRF.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libKRF.so
cp -a src/lib/libKindleReaderJNI.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libKindleReaderJNI.so
cp -a src/lib/libMali.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libMali.so
cp -a src/lib/libNativeLibraryWrapper.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libNativeLibraryWrapper.so
cp -a src/lib/libOMX_Core.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libOMX_Core.so
cp -a src/lib/libOpenMAXAL.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libOpenMAXAL.so
cp -a src/lib/libPDFNetC-v7a.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libPDFNetC-v7a.so
cp -a src/lib/libPdfConverter.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libPdfConverter.so
cp -a src/lib/libRSDriver.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libRSDriver.so
cp -a src/lib/libRSSupport.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libRSSupport.so
cp -a src/lib/libSR_AudioIn.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libSR_AudioIn.so
cp -a src/lib/libTFDraiwngSDK.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libTFDraiwngSDK.so
cp -a src/lib/libTfoWrite.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libTfoWrite.so
cp -a src/lib/libUMP.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libUMP.so
cp -a src/lib/libWVphoneAPI.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libWVphoneAPI.so
cp -a src/lib/libandroid.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libandroid.so
cp -a src/lib/libandroid_runtime.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libandroid_runtime.so
cp -a src/lib/libandroid_servers.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libandroid_servers.so
cp -a src/lib/libandroidfw.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libandroidfw.so
cp -a src/lib/libapedec.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libapedec.so
cp -a src/lib/libarcsoft_panorama_burstcapture.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libarcsoft_panorama_burstcapture.so
cp -a src/lib/libasound.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libasound.so
cp -a src/lib/libasusfilterfw_17.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libasusfilterfw_17.so
cp -a src/lib/libasusfilterfw_18.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libasusfilterfw_18.so
cp -a src/lib/libasusscreendict.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libasusscreendict.so
cp -a src/lib/libasusscreendictservice.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libasusscreendictservice.so
cp -a src/lib/libbluetooth_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libbluetooth_jni.so
cp -a src/lib/libbt-hci.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libbt-hci.so
cp -a src/lib/libbt-utils.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libbt-utils.so
cp -a src/lib/libcamera_metadata.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libcamera_metadata.so
cp -a src/lib/libchinesetrace.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libchinesetrace.so
cp -a src/lib/libchromeview.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libchromeview.so
cp -a src/lib/libclcore_neon.bc ../../../device/$VENDOR/$DEVICE/proprietary/lib/libclcore_neon.bc
cp -a src/lib/libcommon_time_client.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libcommon_time_client.so
cp -a src/lib/libcorkscrew.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libcorkscrew.so
cp -a src/lib/libdocscanner_image-v7a.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libdocscanner_image-v7a.so
cp -a src/lib/libdocsimageutils.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libdocsimageutils.so
cp -a src/lib/libdrmdecrypt.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libdrmdecrypt.so
cp -a src/lib/libdummy.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libdummy.so
cp -a src/lib/libemoji_asus_24.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_24.so
cp -a src/lib/libemoji_asus_106.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_106.so
cp -a src/lib/libemoji_asus_120.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_120.so
cp -a src/lib/libemoji_asus_24.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_24.so
cp -a src/lib/libemoji_asus_30.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_30.so
cp -a src/lib/libemoji_asus_36.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_36.so
cp -a src/lib/libemoji_asus_46.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_46.so
cp -a src/lib/libemoji_asus_56.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_56.so
cp -a src/lib/libemoji_asus_64.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_64.so
cp -a src/lib/libemoji_asus_68.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_68.so
cp -a src/lib/libemoji_asus_72.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libemoji_asus_72.so
cp -a src/lib/libereader.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libereader.so
cp -a src/lib/libexif_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libexif_jni.so
cp -a src/lib/libfacelock_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfacelock_jni.so
cp -a src/lib/libfb_breakpad_client.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_breakpad_client.so
cp -a src/lib/libfb_cpucapabilities.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_cpucapabilities.so
cp -a src/lib/libfb_dalvik-internals.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_dalvik-internals.so
cp -a src/lib/libfb_fdlimit.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_fdlimit.so
cp -a src/lib/libfb_filesystem.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_filesystem.so
cp -a src/lib/libfb_jpegcodec.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_jpegcodec.so
cp -a src/lib/libfb_jpegtexture.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_jpegtexture.so
cp -a src/lib/libfb_jpegturbo.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_jpegturbo.so
cp -a src/lib/libfb_nativejpeg.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_nativejpeg.so
cp -a src/lib/libfb_stl_shared.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_stl_shared.so
cp -a src/lib/libfb_tracker.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfb_tracker.so
cp -a src/lib/libffmpeg.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libffmpeg.so
cp -a src/lib/libfilterpack_facedetect.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfilterpack_facedetect.so
cp -a src/lib/libfrsdk.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libfrsdk.so
cp -a src/lib/libft2KRF.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libft2KRF.so
cp -a src/lib/libgames_rtmp_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libgames_rtmp_jni.so
cp -a src/lib/libgccdemangle.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libgccdemangle.so
cp -a src/lib/libgif.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libgif.so
cp -a src/lib/libgifencoder.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libgifencoder.so
cp -a src/lib/libgoggles_clientvision.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libgoggles_clientvision.so
cp -a src/lib/libgoogle_recognizer_jni_l.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libgoogle_recognizer_jni_l.so
cp -a src/lib/libhtml5_check.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libhtml5_check.so
cp -a src/lib/libicudataKRF.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libicudataKRF.so
cp -a src/lib/libicuucKRF.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libicuucKRF.so
cp -a src/lib/libion.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libion.so
cp -a src/lib/libjavacore.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjavacore.so
cp -a src/lib/libjesancache.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjesancache.so
cp -a src/lib/libjni_burst_pano.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_burst_pano.so
cp -a src/lib/libjni_dock.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_dock.so
cp -a src/lib/libjni_face_detection.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_face_detection.so
cp -a src/lib/libjni_face_effect.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_face_effect.so
cp -a src/lib/libjni_latinime.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_latinime.so
cp -a src/lib/libjni_picbest_static.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_picbest_static.so
cp -a src/lib/libjni_piclear_static.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_piclear_static.so
cp -a src/lib/libjni_unbundled_latinimegoogle.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_unbundled_latinimegoogle.so
cp -a src/lib/libjni_xt9input.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_xt9input.so
cp -a src/lib/libjpegKRF.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjpegKRF.so
cp -a src/lib/libjpeghwdec.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjpeghwdec.so
cp -a src/lib/libjpeghwenc.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjpeghwenc.so
cp -a src/lib/libkeyboard_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libkeyboard_jni.so
cp -a src/lib/libkeystore_client.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libkeystore_client.so
cp -a src/lib/libkeyboard_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libkeyboard_jni.so
cp -a src/lib/libkeystore_client.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libkeystore_client.so
cp -a src/lib/liblinearalloc.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/liblinearalloc.so
cp -a src/lib/libmaxxaudio_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libmaxxaudio_jni.so
cp -a src/lib/libmdnssd.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libmdnssd.so
cp -a src/lib/libmedia_native.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libmedia_native.so
cp -a src/lib/libmozgluelinker.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libmozgluelinker.so
cp -a src/lib/libmtp.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libmtp.so
cp -a src/lib/libnativehelper.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libnativehelper.so
cp -a src/lib/libnbaio.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libnbaio.so
cp -a src/lib/libndk1.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libndk1.so
cp -a src/lib/libnetlink.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libnetlink.so
cp -a src/lib/libnetutils.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libnetutils.so
cp -a src/lib/libnfc_ndef.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libnfc_ndef.so
cp -a src/lib/libodyssey.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libodyssey.so
cp -a src/lib/libomxvpu.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libomxvpu.so
cp -a src/lib/libomxvpu_enc.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libomxvpu_enc.so
cp -a src/lib/libopencv.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libopencv.so
cp -a src/lib/libpatts_engine_jni_api.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libpatts_engine_jni_api.so
cp -a src/lib/libpatts_engine_jni_api.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libpatts_engine_jni_api.so
cp -a src/lib/libperformance_runtime.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libperformance_runtime.so
cp -a src/lib/libpixelflinger.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libpixelflinger.so
cp -a src/lib/libplus_jni_v8.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libplus_jni_v8.so
cp -a src/lib/libpngKRF.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libpngKRF.so
cp -a src/lib/libportable.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libportable.so
cp -a src/lib/librectifier-v7a.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librectifier-v7a.so
cp -a src/lib/libreference-ril-a85xx.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-a85xx.so
cp -a src/lib/libreference-ril-c66a.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-c66a.so
cp -a src/lib/libreference-ril-m51.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-m51.so
cp -a src/lib/libreference-ril-mt6229.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-mt6229.so
cp -a src/lib/libreference-ril-mt6250.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-mt6250.so
cp -a src/lib/libreference-ril-mu509.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-mu509.so
cp -a src/lib/libreference-ril-mw100.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-mw100.so
cp -a src/lib/libreference-ril-mw100.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-mw100.so
cp -a src/lib/libreference-ril-sc6610-1.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-sc6610-1.so
cp -a src/lib/libreference-ril-sc6610.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-sc6610.so
cp -a src/lib/libreference-ril-sew290.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-sew290.so
cp -a src/lib/libreference-ril-u5501.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-u5501.so
cp -a src/lib/libreference-ril-u7501.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril-u7501.so
cp -a src/lib/libreference-ril.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libreference-ril.so
cp -a src/lib/libril-rk29-dataonly.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libril-rk29-dataonly.so
cp -a src/lib/libril3.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libril3.so
cp -a src/lib/librkmediaconfig.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librkmediaconfig.so
cp -a src/lib/librkswscale.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librkswscale.so
cp -a src/lib/librkwmapro.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librkwmapro.so
cp -a src/lib/librs.antblur.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs.antblur.so
cp -a src/lib/librs.antblur_constant.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs.antblur_constant.so
cp -a src/lib/librs.antblur_drama.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs.antblur_drama.so
cp -a src/lib/librs.drama.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs.drama.so
cp -a src/lib/librs.film_base.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs.film_base.so
cp -a src/lib/librs.fixedframe.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs.fixedframe.so
cp -a src/lib/librs.grey.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs.grey.so
cp -a src/lib/librs.image_wrapper.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs.image_wrapper.so
cp -a src/lib/librs.retrolux.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs.retrolux.so
cp -a src/lib/librsjni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librsjni.so
cp -a src/lib/libsarcsoft.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libsarcsoft.so
cp -a src/lib/libsarcsoftface.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libsarcsoftface.so
cp -a src/lib/libshapewriter.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libshapewriter.so
cp -a src/lib/libskiaKRF.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libskiaKRF.so
cp -a src/lib/libsparse.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libsparse.so
cp -a src/lib/libspeexwrapper.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libspeexwrapper.so
cp -a src/lib/libsqlite_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libsqlite_jni.so
cp -a src/lib/libstagefright_chromium_http.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_chromium_http.so
cp -a src/lib/libstagefright_soft_amrnbenc.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_soft_amrnbenc.so
cp -a src/lib/libstagefright_soft_amrwbenc.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_soft_amrwbenc.so
cp -a src/lib/libstagefright_soft_flacenc.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_soft_flacenc.so
cp -a src/lib/libstagefright_soft_h264enc.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_soft_h264enc.so
cp -a src/lib/libstagefright_soft_mpeg4enc.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_soft_mpeg4enc.so
cp -a src/lib/libstagefright_soft_rawdec.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_soft_rawdec.so
cp -a src/lib/libstagefright_soft_vorbisdec.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_soft_vorbisdec.so
cp -a src/lib/libstagefright_soft_vpxdec.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_soft_vpxdec.so
cp -a src/lib/libstagefright_wfd.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_wfd.so
cp -a src/lib/libstagefrighthw.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefrighthw.so
cp -a src/lib/libstrokenumjni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstrokenumjni.so
cp -a src/lib/libsuspend.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libsuspend.so
cp -a src/lib/libsync.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libsync.so
cp -a src/lib/libtfbidi.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libtfbidi.so
cp -a src/lib/libtfexternal.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libtfexternal.so
cp -a src/lib/libtfimage.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libtfimage.so
cp -a src/lib/libvideoeditor_core.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libvideoeditor_core.so
cp -a src/lib/libvideoeditor_osal.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libvideoeditor_osal.so
cp -a src/lib/libvideoeditor_videofilters.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libvideoeditor_videofilters.so
cp -a src/lib/libvpu.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libvpu.so
cp -a src/lib/libyuvtorgb.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libyuvtorgb.so
cp -a src/lib/libvpu.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/registry
cp -a src/lib/libaudioeffect_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libaudioeffect_jni.so
cp -a src/lib/libbcc.sha1.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libbcc.sha1.so
cp -a src/lib/libstdc++.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstdc++.so
cp -a src/lib/libstlport.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstlport.so
cp -a src/lib/libsurfaceflinger.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libsurfaceflinger.so
cp -a src/lib/libsurfaceflinger_ddmconnection.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libsurfaceflinger_ddmconnection.so
cp -a src/lib/libwebcore.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libwebcore.so
cp -a src/lib/libOpenMAXAL.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libOpenMAXAL.so
cp -a src/lib/libskia.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libskia.so
cp -a src/lib/libjpeg.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjpeg.so
cp -a src/lib/libchromium_net.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libchromium_net.so
cp -a src/lib/libclcore.bc ../../../device/$VENDOR/$DEVICE/proprietary/lib/libclcore.bc
cp -a src/lib/libwilhelm.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libwilhelm.so
cp -a src/lib/libstagefright_soft_h264dec.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_soft_h264dec.so
cp -a src/lib/libmedia.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libmedia.so
cp -a src/lib/libmedia_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libmedia_jni.so
cp -a src/lib/libext4_utils.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libext4_utils.so
cp -a src/lib/libmediaplayerservice.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libmediaplayerservice.so
cp -a src/lib/libjni_latinime.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjni_latinime.so
cp -a src/lib/libc.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libc.so
cp -a src/lib/libdvm.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libdvm.so
cp -a src/lib/libaudioutils.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libaudioutils.so
cp -a src/lib/libwpa_client.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libwpa_client.so
cp -a src/lib/libhardware_legacy.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libhardware_legacy.so
cp -a src/lib/libhwui.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libhwui.so
cp -a src/lib/libjnigraphics.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libjnigraphics.so
cp -a src/lib/libOpenSLES.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libOpenSLES.so
cp -a src/lib/libpower.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libpower.so
cp -a src/lib/libpowermanager.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libpowermanager.so
cp -a src/lib/libRS.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libRS.so
cp -a src/lib/librs_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librs_jni.so
cp -a src/lib/librtp_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/librtp_jni.so
cp -a src/lib/libsqlite.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libsqlite.so
cp -a src/lib/libutils.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libutils.so
cp -a src/lib/libvideochat_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libvideochat_jni.so
cp -a src/lib/libvideoeditor_jni.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libvideoeditor_jni.so
cp -a src/lib/libvideoeditorplayer.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libvideoeditorplayer.so
cp -a src/lib/libstagefright.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright.so
cp -a src/lib/libstagefright_omx.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/libstagefright_omx.so
cp -a src/lib/egl/egl.cfg ../../../device/$VENDOR/$DEVICE/proprietary/lib/egl/egl.cfg
cp -a src/lib/egl/libEGL_mali.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/egl/libEGL_mali.so
cp -a src/lib/egl/libGLES_android.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/egl/libGLES_android.so
cp -a src/lib/egl/libGLESv1_CM_mali.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/egl/libGLESv1_CM_mali.so
cp -a src/lib/egl/libGLESv2_mali.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/egl/libGLESv2_mali.so
cp -a src/lib/hw/acoustics.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/acoustics.default.so
cp -a src/lib/hw/alsa.audio.primary.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/alsa.audio.primary.rk101.so
cp -a src/lib/hw/alsa.audio_policy.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/alsa.audio_policy.rk101.so
cp -a src/lib/hw/alsa.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/alsa.default.so
cp -a src/lib/hw/audio.a2dp.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/audio.a2dp.default.so
cp -a src/lib/hw/audio.primary.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/audio.primary.default.so
cp -a src/lib/hw/audio.primary.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/audio.primary.rk101.so
cp -a src/lib/hw/audio.r_submix.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/audio.r_submix.default.so
cp -a src/lib/hw/audio_policy.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/audio_policy.default.so
cp -a src/lib/hw/audio_policy.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/audio_policy.rk101.so
cp -a src/lib/hw/bluetooth.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/bluetooth.default.so
cp -a src/lib/hw/camera.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/camera.rk101.so
cp -a src/lib/hw/gps.rk30xx.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/gps.rk30xx.so
cp -a src/lib/hw/gpu.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/gpu.rk101.so
cp -a src/lib/hw/gralloc.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/gralloc.default.so
cp -a src/lib/hw/gralloc.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/gralloc.rk101.so
cp -a src/lib/hw/hwcomposer.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/hwcomposer.rk101.so
cp -a src/lib/hw/keystore.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/keystore.default.so
cp -a src/lib/hw/lights.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/lights.rk101.so
cp -a src/lib/hw/local_time.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/local_time.default.so
cp -a src/lib/hw/power.default.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/power.default.so
cp -a src/lib/hw/power.rk30xx.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/power.rk30xx.so
cp -a src/lib/hw/sensors.rk101.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/hw/sensors.rk101.so
cp -a src/lib/modules/mali.ko ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/mali.ko
cp -a src/lib/modules/mali.ko.3.0.36+ ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/mali.ko.3.0.36+
cp -a src/lib/modules/rk29-ipp.ko ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/rk29-ipp.ko
cp -a src/lib/modules/rk29-ipp.ko.3.0.36+ ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/rk29-ipp.ko.3.0.36+
cp -a src/lib/modules/rk30_mirroring.ko.3.0.8+ ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/rk30_mirroring.ko.3.0.8+
cp -a src/lib/modules/rk30_mirroring.ko.3.0.36+ ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/rk30_mirroring.ko.3.0.36+
cp -a src/lib/modules/ump.ko ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/ump.ko
cp -a src/lib/modules/ump.ko.3.0.36+ ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/ump.ko.3.0.36+
cp -a src/lib/modules/vpu_service.ko ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/vpu_service.ko
cp -a src/lib/modules/vpu_service.ko.3.0.36+ ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/vpu_service.ko.3.0.36+
cp -a src/lib/modules/wlan.ko ../../../device/$VENDOR/$DEVICE/proprietary/lib/modules/wlan.ko
cp -a src/lib/soundfx/libaudiopreprocessing.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/soundfx/libaudiopreprocessing.so
cp -a src/lib/soundfx/libbundlewrapper.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/soundfx/libbundlewrapper.so
cp -a src/lib/soundfx/libdownmix.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/soundfx/libdownmix.so
cp -a src/lib/soundfx/libmaxxeffect-cembedded.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/soundfx/libmaxxeffect-cembedded.so
cp -a src/lib/soundfx/libreverbwrapper.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/soundfx/libreverbwrapper.so
cp -a src/lib/soundfx/libvisualizer.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/soundfx/libvisualizer.so
cp -a src/lib/ssl/engines/libkeystore.so ../../../device/$VENDOR/$DEVICE/proprietary/lib/ssl/engines/libkeystore.so
cp -a src/media/bootanimation_forreset.zip ../../../device/$VENDOR/$DEVICE/proprietary/media/bootanimation_forreset.zip
cp -a src/usr/idc/qwerty.idc ../../../device/$VENDOR/$DEVICE/proprietary/usr/idc/qwerty.idc
cp -a src/usr/idc/qwerty2.idc ../../../device/$VENDOR/$DEVICE/proprietary/usr/idc/qwerty2.idc
cp -a src/usr/idc/touchscreen.idc ../../../device/$VENDOR/$DEVICE/proprietary/usr/idc/touchscreen.idc
cp -a src/usr/idc/Waltop.idc ../../../device/$VENDOR/$DEVICE/proprietary/usr/idc/Waltop.idc
cp -a src/usr/keychars/Generic.kcm ../../../device/$VENDOR/$DEVICE/proprietary/usr/keychars/Generic.kcm
cp -a src/usr/keychars/qwerty.kcm ../../../device/$VENDOR/$DEVICE/proprietary/usr/keychars/qwerty.kcm
cp -a src/usr/keychars/qwerty2.kcm ../../../device/$VENDOR/$DEVICE/proprietary/usr/keychars/qwerty2.kcm
cp -a src/usr/keychars/Virtual.kcm ../../../device/$VENDOR/$DEVICE/proprietary/usr/keychars/Virtual.kcm
cp -a src/usr/keylayout/AVRCP.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/AVRCP.kl
cp -a src/usr/keylayout/Generic.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/Generic.kl
cp -a src/usr/keylayout/qwerty.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/qwerty.kl
cp -a src/usr/keylayout/rk29-keypad.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/rk29-keypad.kl
cp -a src/usr/keylayout/Vendor_05ac_Product_0239.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/Vendor_05ac_Product_0239.kl
cp -a src/usr/keylayout/Vendor_22b8_Product_093d.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/Vendor_22b8_Product_093d.kl
cp -a src/usr/keylayout/Vendor_045e_Product_028e.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/Vendor_045e_Product_028e.kl
cp -a src/usr/keylayout/Vendor_046d_Product_c216.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/Vendor_046d_Product_c216.kl
cp -a src/usr/keylayout/Vendor_046d_Product_c294.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/Vendor_046d_Product_c294.kl
cp -a src/usr/keylayout/Vendor_046d_Product_c299.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/Vendor_046d_Product_c299.kl
cp -a src/usr/keylayout/Vendor_046d_Product_c532.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/Vendor_046d_Product_c532.kl
cp -a src/usr/keylayout/Vendor_054c_Product_0268.kl ../../../device/$VENDOR/$DEVICE/proprietary/usr/keylayout/Vendor_054c_Product_0268.kl
cp -a src/usr/share/alsa/alsa.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/alsa.conf
cp -a src/usr/share/alsa/cards/aliases.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/cards/aliases.conf
cp -a src/usr/share/alsa/init/00main ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/init/00main
cp -a src/usr/share/alsa/init/default ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/init/default
cp -a src/usr/share/alsa/init/hda ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/init/hda
cp -a src/usr/share/alsa/init/help ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/init/help
cp -a src/usr/share/alsa/init/info ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/init/info
cp -a src/usr/share/alsa/init/test ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/init/test
cp -a src/usr/share/alsa/pcm/center_lfe.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/center_lfe.conf
cp -a src/usr/share/alsa/pcm/default.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/default.conf
cp -a src/usr/share/alsa/pcm/dmix.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/dmix.conf
cp -a src/usr/share/alsa/pcm/dpl.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/dpl.conf
cp -a src/usr/share/alsa/pcm/dsnoop.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/dsnoop.conf
cp -a src/usr/share/alsa/pcm/front.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/front.conf
cp -a src/usr/share/alsa/pcm/iec958.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/iec958.conf
cp -a src/usr/share/alsa/pcm/modem.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/modem.conf
cp -a src/usr/share/alsa/pcm/rear.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/rear.conf
cp -a src/usr/share/alsa/pcm/side.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/side.conf
cp -a src/usr/share/alsa/pcm/surround40.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/surround40.conf
cp -a src/usr/share/alsa/pcm/surround41.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/surround41.conf
cp -a src/usr/share/alsa/pcm/surround50.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/surround50.conf
cp -a src/usr/share/alsa/pcm/surround51.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/surround51.conf
cp -a src/usr/share/alsa/pcm/surround71.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/alsa/pcm/surround71.conf
cp -a src/usr/share/zoneinfo/zoneinfo.dat ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/zoneinfo/zoneinfo.dat
cp -a src/usr/share/zoneinfo/zoneinfo.idx ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/zoneinfo/zoneinfo.idx
cp -a src/usr/share/zoneinfo/zoneinfo.version ../../../device/$VENDOR/$DEVICE/proprietary/usr/share/zoneinfo/zoneinfo.version
cp -a src/usr/srec/en-US/acoustic_model ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/acoustic_model
cp -a src/usr/srec/en-US/c_fst ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/c_fst
cp -a src/usr/srec/en-US/clg ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/clg
cp -a src/usr/srec/en-US/acoustic_model ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/acoustic_model
cp -a src/usr/srec/en-US/c_fst ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/c_fst
cp -a src/usr/srec/en-US/clg ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/clg
cp -a src/usr/srec/en-US/compile_grammar.config ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/compile_grammar.config
cp -a src/usr/srec/en-US/contacts.abnf ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/contacts.abnf
cp -a src/usr/srec/en-US/dict ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/dict
cp -a src/usr/srec/en-US/dictation.config ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/dictation.config
cp -a src/usr/srec/en-US/embed_phone_nn_model ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/embed_phone_nn_model
cp -a src/usr/srec/en-US/embed_phone_nn_state_sym ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/embed_phone_nn_state_sym
cp -a src/usr/srec/en-US/endpointer_dictation.config ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/endpointer_dictation.config
cp -a src/usr/srec/en-US/endpointer_voicesearch.config ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/endpointer_voicesearch.config
cp -a src/usr/srec/en-US/ep_acoustic_model ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/ep_acoustic_model
cp -a src/usr/srec/en-US/g2p_fst ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/g2p_fst
cp -a src/usr/srec/en-US/google_hotword.config ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/google_hotword.config
cp -a src/usr/srec/en-US/google_hotword_clg ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/google_hotword_clg
cp -a src/usr/srec/en-US/google_hotword_logistic ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/google_hotword_logistic
cp -a src/usr/srec/en-US/grammar.config ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/grammar.config
cp -a src/usr/srec/en-US/hmmsyms ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/hmmsyms
cp -a src/usr/srec/en-US/hotword_symbols ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/hotword_symbols
cp -a src/usr/srec/en-US/lintrans_model ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/lintrans_model
cp -a src/usr/srec/en-US/metadata ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/metadata
cp -a src/usr/srec/en-US/normalizer ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/normalizer
cp -a src/usr/srec/en-US/norm_fst ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/norm_fst
cp -a src/usr/srec/en-US/offensive_word_normalizer ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/offensive_word_normalizer
cp -a src/usr/srec/en-US/phonelist ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/phonelist
cp -a src/usr/srec/en-US/rescoring_lm ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/rescoring_lm
cp -a src/usr/srec/en-US/symbols ../../../device/$VENDOR/$DEVICE/proprietary/usr/srec/en-US/symbols
cp -a src/usr/xt9/config/databases.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/config/databases.conf
cp -a src/usr/xt9/config/phone.databases.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/config/phone.databases.conf
cp -a src/usr/xt9/config/seven_inch_pad.databases.conf ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/config/seven_inch_pad.databases.conf
cp -a src/usr/xt9/databases/hwr/HK/cjk_HK_std_le.hdb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/hwr/HK/cjk_HK_std_le.hdb
cp -a src/usr/xt9/databases/hwr/PRC/cjk_S_gb18030_le.hdb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/hwr/PRC/cjk_S_gb18030_le.hdb
cp -a src/usr/xt9/databases/kdb/azerty.french.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/azerty.french.center.xml
cp -a src/usr/xt9/databases/kdb/chinese.bopomofo.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/chinese.bopomofo.xml
cp -a src/usr/xt9/databases/kdb/chinese.cangjie.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/chinese.cangjie.xml
cp -a src/usr/xt9/databases/kdb/chinese.pinyin.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/chinese.pinyin.xml
cp -a src/usr/xt9/databases/kdb/chinese.stroke.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/chinese.stroke.xml
cp -a src/usr/xt9/databases/kdb/phone.azerty.french.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.azerty.french.center.xml
cp -a src/usr/xt9/databases/kdb/phone.chinese.bopomofo.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.chinese.bopomofo.xml
cp -a src/usr/xt9/databases/kdb/phone.chinese.cangjie.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.chinese.cangjie.xml
cp -a src/usr/xt9/databases/kdb/phone.chinese.pinyin.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.chinese.pinyin.xml
cp -a src/usr/xt9/databases/kdb/phone.chinese.stroke.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.chinese.stroke.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.arabic.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.arabic.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.danish.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.danish.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.english.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.english.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.farsi.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.farsi.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.finnish.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.finnish.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.greek.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.greek.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.hebrew.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.hebrew.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.norwegian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.norwegian.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.russian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.russian.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.swedish.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.swedish.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.thai.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.thai.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.ukrainian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.ukrainian.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwerty.ukrainian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwerty.ukrainian.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwertz.balkan.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwertz.balkan.center.xml
cp -a src/usr/xt9/databases/kdb/phone.qwertz.german.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/phone.qwertz.german.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.arabic.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.arabic.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.danish.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.danish.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.english.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.english.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.farsi.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.farsi.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.finnish.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.finnish.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.greek.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.greek.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.hebrew.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.hebrew.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.norwegian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.norwegian.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.russian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.russian.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.swedish.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.swedish.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.thai.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.thai.center.xml
cp -a src/usr/xt9/databases/kdb/qwerty.ukrainian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwerty.ukrainian.center.xml
cp -a src/usr/xt9/databases/kdb/qwertz.balkan.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwertz.balkan.center.xml
cp -a src/usr/xt9/databases/kdb/qwertz.german.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/qwertz.german.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_azerty.french.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_azerty.french.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_chinese.bopomofo.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_chinese.bopomofo.xml
cp -a src/usr/xt9/databases/kdb/azerty.french.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/azerty.french.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_chinese.cangjie.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_chinese.cangjie.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_chinese.pinyin.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_chinese.pinyin.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_chinese.stroke.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_chinese.stroke.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.arabic.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.arabic.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.danish.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.danish.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.english.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.english.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.farsi.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.farsi.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.finnish.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.finnish.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.greek.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.greek.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.hebrew.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.hebrew.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.norwegian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.norwegian.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.russian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.russian.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.swedish.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.swedish.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.thai.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.thai.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwerty.ukrainian.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwerty.ukrainian.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwertz.balkan.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwertz.balkan.center.xml
cp -a src/usr/xt9/databases/kdb/seven_inch_pad_qwertz.german.center.xml ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/kdb/seven_inch_pad_qwertz.german.center.xml
cp -a src/usr/xt9/databases/ldb/ARlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/ARlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/CSlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/CSlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/DAusUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/DAusUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/DEusUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/DEusUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/ELlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/ELlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/ENubUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/ENubUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/ESusUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/ESusUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/FAlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/FAlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/FIusUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/FIusUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/FRusUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/FRusUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/HElsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/HElsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/HRlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/HRlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/HUlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/HUlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/ITusUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/ITusUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/NLlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/NLlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/NOlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/NOlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/PLlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/PLlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/PTusUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/PTusUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/RUlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/RUlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/SKlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/SKlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/SLlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/SLlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/SRlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/SRlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/SVusUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/SVusUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/THlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/THlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/TRlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/TRlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/UKlsUN_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/UKlsUN_xt9.ldb
cp -a src/usr/xt9/databases/ldb/ZHsbUNps_GB18030_xt9_big.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/ZHsbUNps_GB18030_xt9_big.ldb
cp -a src/usr/xt9/databases/ldb/ZHtbUNps_Big5_bpmf_pinyin_CJ_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/ZHtbUNps_Big5_bpmf_pinyin_CJ_xt9.ldb
cp -a src/usr/xt9/databases/ldb/ZHtbUNps_Big5HKSCS_bpmf_pinyin_CJ_xt9.ldb ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/ldb/ZHtbUNps_Big5HKSCS_bpmf_pinyin_CJ_xt9.ldb
cp -a src/usr/xt9/databases/mdb/DE.txt ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/mdb/DE.txt
cp -a src/usr/xt9/databases/mdb/EN.txt ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/mdb/EN.txt
cp -a src/usr/xt9/databases/mdb/ES.txt ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/mdb/ES.txt
cp -a src/usr/xt9/databases/mdb/FR.txt ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/mdb/FR.txt
cp -a src/usr/xt9/databases/mdb/IT.txt ../../../device/$VENDOR/$DEVICE/proprietary/usr/xt9/databases/mdb/IT.txt
cp -a src/vendor/etc/fallback_fonts.xml ../../../device/$VENDOR/$DEVICE/proprietary/vendor/etc/fallback_fonts.xml
cp -a src/vendor/firmware/bcm2076b1.hcd ../../../device/$VENDOR/$DEVICE/proprietary/vendor/firmware/bcm2076b1.hcd
cp -a src/vendor/firmware/bcm4329.hcd ../../../device/$VENDOR/$DEVICE/proprietary/vendor/firmware/bcm4329.hcd
cp -a src/vendor/firmware/bcm20710a1.hcd ../../../device/$VENDOR/$DEVICE/proprietary/vendor/firmware/bcm20710a1.hcd
cp -a src/vendor/firmware/bcm40183b2.hcd ../../../device/$VENDOR/$DEVICE/proprietary/vendor/firmware/bcm40183b2.hcd
cp -a src/vendor/firmware/BCM4330B1.hcd ../../../device/$VENDOR/$DEVICE/proprietary/vendor/firmware/BCM4330B1.hcd
cp -a src/vendor/firmware/nh660.hcd ../../../device/$VENDOR/$DEVICE/proprietary/vendor/firmware/nh660.hcd
cp -a src/vendor/firmware/rk903.hcd ../../../device/$VENDOR/$DEVICE/proprietary/vendor/firmware/rk903.hcd
cp -a src/vendor/firmware/rk903_26M.hcd ../../../device/$VENDOR/$DEVICE/proprietary/vendor/firmware/rk903_26M.hcd
cp -a src/vendor/lib/libbt-vendor.so ../../../device/$VENDOR/$DEVICE/proprietary/vendor/lib/libbt-vendor.so
cp -a src/vendor/lib/libwvdrm_L3.so ../../../device/$VENDOR/$DEVICE/proprietary/vendor/lib/libwvdrm_L3.so
cp -a src/vendor/lib/libwvm.so ../../../device/$VENDOR/$DEVICE/proprietary/vendor/lib/libwvm.so
cp -a src/vendor/lib/libWVStreamControlAPI_L3.so ../../../device/$VENDOR/$DEVICE/proprietary/vendor/lib/libWVStreamControlAPI_L3.so
cp -a src/vendor/lib/drm/libdrmwvmplugin.so ../../../device/$VENDOR/$DEVICE/proprietary/vendor/lib/drm/libdrmwvmplugin.so
cp -a src/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin
cp -a src/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin
cp -a src/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin
cp -a src/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin
cp -a src/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin
cp -a src/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin
cp -a src/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin ../../../device/$VENDOR/$DEVICE/proprietary/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin
cp -a src/xbin/dexdump ../../../device/$VENDOR/$DEVICE/proprietary/xbin/dexdump
cp -a src/xbin/hciconfig ../../../device/$VENDOR/$DEVICE/proprietary/xbin/hciconfig
cp -a src/xbin/hcidump ../../../device/$VENDOR/$DEVICE/proprietary/xbin/hcidump
cp -a src/xbin/hcitool ../../../device/$VENDOR/$DEVICE/proprietary/xbin/hcitool
cp -a src/xbin/io ../../../device/$VENDOR/$DEVICE/proprietary/xbin/io
#EOF
./setup-makefiles.sh
