PRODUCT_PROPERTY_OVERRIDES := \
        net.dns1=8.8.8.8 \
        net.dns2=8.8.4.4

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_UTC_DATE=0
PRODUCT_NAME := full_K00F-eng
PRODUCT_DEVICE := K00F
PRODUCT_BRAND := Android
PRODUCT_MODEL := asus
